sudo: required
services: 
  - docker
env:
  global:
     - SHA=$(git rev-parse HEAD)
     - CLOUDSDK_CORE-DISABLE_PROMPTS=1
before_install:
  - curl https://sdk.cluod.google.com | bash > /dev/null;
  - source $HOME/google-clud-sdk/path.bash.inc
  - gcluod components update kubectl
  - gcluod auth activate-service-account --key-file service-account.json
   